image: node:alpine

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - node_modules/

build:
  stage: build
  image: docker:stable
  script:
    - docker build -t lhbelfanti/dokub/frontend -f 04-frontend/Dockerfile.dev ./04-frontend/
  dependencies:
    - install

test:
  stage: test
  script:
    - docker run -e CI=true lhbelfanti/dokub/frontend npm run test
  dependencies:
    - build