image: node:alpine


stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t lhbelfanti/dokub/frontend -f 04-frontend/Dockerfile.dev ./04-frontend/

test:
  stage: test
  script:
    - docker run -e CI=true lhbelfanti/dokub/frontend npm run test
  dependencies:
    - build