sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lhbelfanti/react-test -f ./05-complex/client/Dockerfile.dev ./05-complex/client

script:
  - docker run -e CI=true lhbelfanti/react-test npm test

after_success:
  - docker build -t lhbelfanti/multi-client ./05-complex/client
  - docker build -t lhbelfanti/multi-nginx ./05-complex/nginx
  - docker build -t lhbelfanti/multi-server ./05-complex/server
  - docker build -t lhbelfanti/multi-worker ./05-complex/worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lhbelfanti/multi-client
  - docker push lhbelfanti/multi-nginx
  - docker push lhbelfanti/multi-server
  - docker push lhbelfanti/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-149011651000'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY